export const data = [
  {
    id: 1,
    title: "REQ123",
    status: "Pending",
    plan: "Basic",
    amount: "100",
    type: "Subscription",
    createdAt: "2024-07-01T12:34:56Z",
    label: "pending",
    email: "user1@example.com",
  },
  {
    id: 2,
    title: "REQ124",
    status: "Completed",
    plan: "Pro",
    amount: "200",
    type: "One-time",
    createdAt: "2024-07-02T15:20:30Z",
    label: "completed",
    email: "user2@example.com",
  },
  {
    id: 3,
    title: "REQ125",
    status: "In Progress",
    plan: "Enterprise",
    amount: "300",
    type: "Subscription",
    createdAt: "2024-07-03T10:00:00Z",
    label: "in-progress",
    email: "user3@example.com",
  },
  {
    id: 4,
    title: "REQ126",
    status: "Pending",
    plan: "Basic",
    amount: "400",
    type: "One-time",
    createdAt: "2024-07-04T14:50:15Z",
    label: "pending",
    email: "user4@example.com",
  },
  {
    id: 5,
    title: "REQ127",
    status: "Completed",
    plan: "Pro",
    amount: "500",
    type: "Subscription",
    createdAt: "2024-07-05T09:45:30Z",
    label: "completed",
    email: "user5@example.com",
  },
];
