export const data = [
  {
    id: 1,
    subject:
      "Subject 1 This is the message for Subject 1 This is the message for Subject 1 This is the message for Subject 1",
    message: "This is the message for Subject 1",
    name: "John Doe",
    email: "john.doe@example.com",
    contact: "123-456-7890",
    createdAt: "2024-01-01",
  },
  {
    id: 2,
    subject: "Subject 2",
    message: "This is the message for Subject 2",
    name: "Jane Smith",
    email: "jane.smith@example.com",
    contact: "098-765-4321",
    createdAt: "2024-02-01",
  },
  {
    id: 3,
    subject: "Subject 3",
    message: "This is the message for Subject 3",
    name: "Alice Johnson",
    email: "alice.johnson@example.com",
    contact: "555-555-5555",
    createdAt: "2024-03-01",
  },
  {
    id: 4,
    subject: "Subject 4",
    message: "This is the message for Subject 4",
    name: "Bob Brown",
    email: "bob.brown@example.com",
    contact: "111-222-3333",
    createdAt: "2024-04-01",
  },
  {
    id: 5,
    subject: "Subject 5",
    message: "This is the message for Subject 5",
    name: "Carol White",
    email: "carol.white@example.com",
    contact: "666-777-8888",
    createdAt: "2024-05-01",
  },
];
