export const data = [
  {
    id: 1,
    name: "PayPal",
    status: "test",
    icon: "https://cdn-icons-png.flaticon.com/512/174/174861.png",
    key: "somethign",
    saltKey: "hellohh",
  },
  {
    id: 2,
    name: "Stripe",
    status: "test",
    icon: "icon",
    key: "somethign",
    saltKey: "hellohh",
  },
  {
    id: 3,
    name: "Square",
    status: "test",
    icon: "icon",
    key: "somethign",
    saltKey: "hellohh",
  },
  {
    id: 4,
    name: "Authorize.Net",
    status: "live",
    icon: "icon",
    key: "somethign",
    saltKey: "hellohh",
  },
  {
    id: 5,
    name: "Amazon Pay",
    status: "live",
    icon: "icon",
    key: "somethign",
    saltKey: "hellohh",
  },
];
